name: "Auto-Approve Website Update PRs"

on:
  pull_request_target:
    branches:
      - main

jobs:
  approve-pr-if-website-update:
    name: Approve PR if Website Update from GitHub Actions
    if: github.event.pull_request.user.id == 41898282 && github.event.pull_request.title == 'Automatic Website Update'
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Token
        id: app-token-generation
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5
        with:
          app-id: ${{ secrets.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}

      - name: GitHub API Call
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/pulls/${{github.event.number}}/reviews \
          --header 'authorization: Bearer ${{ steps.app-token-generation.outputs.token }}' \
          --header 'content-type: application/json' \
          -d '{"event":"APPROVE"}' \
          --fail

      - name: Enable Automerge
        uses: daneden/enable-automerge-action@f8558b65c5b8d8bfb592c4e74e3d491624a38fbd #v1.0.2-ish
        with:
          github-token: ${{ steps.app-token-generation.outputs.token }}
